name: lint
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      - uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout=5m
          version: latest
  gherkin-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: restqa/gherkin-linter-action@0.0.1
        with:
          path: "features/"
          config_file: "features/.gherkin-lintrc"
